from . import res_user
from . import hr_employee
from . import hr_payroll
from . import hr_attendance
from . import hr_leave
from . import hr_performance
from . import hr_wiba
from . import hr_injury
from . import hr_blacklist
from . import hr_document
from . import crm_lead
from . import accounting_invoice
from . import inventory_product
from . import ehs_incident
from . import ehs_compliance
from . import ehs_inspection
from . import ehs_alert
from . import engineering_project
from . import engineering_contract
from . import engineering_claim
from . import engineering_variation
from . import engineering_payment
from . import engineering_dispute
from . import engineering_warning
from . import transport_vehicle
from . import transport_driver
from . import transport_shipment
from . import fuel_entry
from . import job_job
from . import job_applicant
from . import job_interview
from . import network_post
from . import network_job
