from . import res_user
from . import hr_employee
from . import hr_payroll
from . import hr_attendance
from . import hr_leave
from . import hr_performance
from . import hr_wiba
from . import hr_injury
from . import hr_blacklist
from . import hr_document
from . import crm_lead
from . import accounting_invoice
from . import inventory_product
from . import ehs_incident
from . import ehs_compliance
from . import ehs_inspection
from . import ehs_alert
from . import engineering_project
from . import engineering_contract
from . import engineering_claim
from . import engineering_variation
from . import engineering_payment
from . import engineering_dispute
from . import engineering_warning
from . import transport_vehicle
from . import transport_driver
from . import transport_shipment
from . import fuel_entry
from . import job_job
from . import job_applicant
from . import job_interview
from . import network_post
from . import network_job
from . import network_profile
from . import network_core
from . import career_data
from . import network_growth
from . import org_department
from . import hr_loan
from . import hr_expense
from . import hr_holiday
from . import hr_leave_policy
from . import hr_exchange_rate
from . import hr_statutory_number
from . import hr_notification
from . import hr_bonus
from . import hr_terminal_benefit
from . import hr_casual_worker
from . import hr_overtime_policy
from . import hr_salary_structure
from . import hr_employee_benefit
from . import hr_disciplinary
from . import hr_training
from . import hr_asset
from . import hr_exit
from . import hr_job_requisition
from . import hr_employee_classification
from . import payment_gateway
from . import bank_settlement
from . import network_tap
