type StateEntry = { name: string; cities: string[] };

const countryStates: Record<string, StateEntry[]> = {
  ke: [
    { name: 'Nairobi', cities: ['Nairobi CBD', 'Westlands', 'Kilimani', 'Karen', 'Langata', 'Eastleigh', 'South B', 'South C', 'Umoja', 'Embakasi'] },
    { name: 'Mombasa', cities: ['Mombasa Island', 'Nyali', 'Bamburi', 'Changamwe', 'Likoni', 'Kisauni'] },
    { name: 'Kisumu', cities: ['Kisumu Central', 'Milimani', 'Kondele', 'Nyalenda', 'Manyatta'] },
    { name: 'Nakuru', cities: ['Nakuru Town', 'Lanet', 'Nakuru East', 'Nakuru West'] },
    { name: 'Kiambu', cities: ['Kiambu Town', 'Thika', 'Ruiru', 'Limuru', 'Juja', 'Kikuyu'] },
    { name: 'Machakos', cities: ['Machakos Town', 'Athi River', 'Mavoko', 'Kangundo'] },
    { name: 'Uasin Gishu', cities: ['Eldoret', 'Kapseret', 'Kesses'] },
    { name: 'Meru', cities: ['Meru Town', 'Nkubu', 'Maua'] },
    { name: 'Kilifi', cities: ['Kilifi Town', 'Malindi', 'Watamu'] },
    { name: 'Nandi', cities: ['Kapsabet', 'Nandi Hills', 'Kabiyet'] },
  ],
  ng: [
    { name: 'Lagos', cities: ['Ikeja', 'Victoria Island', 'Lekki', 'Surulere', 'Yaba', 'Ikoyi', 'Apapa', 'Mushin', 'Oshodi', 'Ajegunle'] },
    { name: 'Abuja', cities: ['Garki', 'Wuse', 'Maitama', 'Asokoro', 'Gwarinpa', 'Kubwa'] },
    { name: 'Rivers', cities: ['Port Harcourt', 'Obio-Akpor', 'Eleme', 'Okrika'] },
    { name: 'Oyo', cities: ['Ibadan', 'Oyo Town', 'Ogbomosho'] },
    { name: 'Kano', cities: ['Kano City', 'Nasarawa', 'Fagge', 'Dala'] },
    { name: 'Delta', cities: ['Warri', 'Asaba', 'Ughelli', 'Sapele'] },
    { name: 'Edo', cities: ['Benin City', 'Auchi', 'Ekpoma'] },
    { name: 'Kaduna', cities: ['Kaduna South', 'Kaduna North', 'Zaria'] },
    { name: 'Ogun', cities: ['Abeokuta', 'Sagamu', 'Ijebu Ode'] },
    { name: 'Enugu', cities: ['Enugu City', 'Nsukka', 'Awgu'] },
  ],
  za: [
    { name: 'Gauteng', cities: ['Johannesburg', 'Pretoria', 'Midrand', 'Soweto', 'Centurion', 'Sandton'] },
    { name: 'Western Cape', cities: ['Cape Town', 'Stellenbosch', 'Paarl', 'George', 'Worcester'] },
    { name: 'KwaZulu-Natal', cities: ['Durban', 'Pietermaritzburg', 'Richards Bay', 'Newcastle'] },
    { name: 'Eastern Cape', cities: ['Gqeberha', 'East London', 'Mthatha'] },
    { name: 'Free State', cities: ['Bloemfontein', 'Welkom', 'Bethlehem'] },
    { name: 'Limpopo', cities: ['Polokwane', 'Tzaneen', 'Mokopane'] },
    { name: 'Mpumalanga', cities: ['Mbombela', 'Emalahleni', 'Secunda'] },
    { name: 'North West', cities: ['Mahikeng', 'Klerksdorp', 'Rustenburg'] },
    { name: 'Northern Cape', cities: ['Kimberley', 'Upington'] },
  ],
  gh: [
    { name: 'Greater Accra', cities: ['Accra', 'Tema', 'Madina', 'Adenta', 'Ashaiman'] },
    { name: 'Ashanti', cities: ['Kumasi', 'Obuasi', 'Mampong'] },
    { name: 'Western', cities: ['Sekondi-Takoradi', 'Axim', 'Half Assini'] },
    { name: 'Central', cities: ['Cape Coast', 'Winneba', 'Mankessim'] },
    { name: 'Eastern', cities: ['Koforidua', 'Nkawkaw', 'Akosombo'] },
    { name: 'Volta', cities: ['Ho', 'Hohoe', 'Aflao'] },
    { name: 'Northern', cities: ['Tamale', 'Yendi', 'Bimbilla'] },
    { name: 'Upper East', cities: ['Bolgatanga', 'Navrongo', 'Bawku'] },
  ],
  tz: [
    { name: 'Dar es Salaam', cities: ['Kinondoni', 'Ilala', 'Temeke', 'Ubungo', 'Kigamboni'] },
    { name: 'Arusha', cities: ['Arusha City', 'Meru', 'Arusha CBD'] },
    { name: 'Mwanza', cities: ['Mwanza City', 'Ilemela', 'Nyamagana'] },
    { name: 'Zanzibar', cities: ['Zanzibar City', 'Mkoani', 'Wete'] },
    { name: 'Mbeya', cities: ['Mbeya City', 'Mbalizi'] },
    { name: 'Dodoma', cities: ['Dodoma City', 'Msalato', 'Dodoma Central'] },
    { name: 'Tanga', cities: ['Tanga City', 'Muheza'] },
    { name: 'Kilimanjaro', cities: ['Moshi', 'Moshi Rural'] },
  ],
  ug: [
    { name: 'Central', cities: ['Kampala', 'Entebbe', 'Mukono', 'Wakiso', 'Nansana'] },
    { name: 'Eastern', cities: ['Jinja', 'Mbale', 'Tororo', 'Soroti'] },
    { name: 'Northern', cities: ['Gulu', 'Lira', 'Arua', 'Kitgum'] },
    { name: 'Western', cities: ['Mbarara', 'Kasese', 'Fort Portal', 'Kabale'] },
  ],
  rw: [
    { name: 'Kigali', cities: ['Gasabo', 'Nyarugenge', 'Kicukiro'] },
    { name: 'Eastern', cities: ['Rwamagana', 'Nyagatare', 'Kayonza'] },
    { name: 'Western', cities: ['Rubavu', 'Rusizi', 'Karuongi'] },
    { name: 'Northern', cities: ['Musanze', 'Gicumbi', 'Burera'] },
    { name: 'Southern', cities: ['Huye', 'Nyanza', 'Ruhango'] },
  ],
  et: [
    { name: 'Addis Ababa', cities: ['Addis Ketema', 'Bole', 'Kirkos', 'Yeka', 'Lideta', 'Nifas Silk'] },
    { name: 'Oromia', cities: ['Adama', 'Jimma', 'Shashamane', 'Bishoftu'] },
    { name: 'Amhara', cities: ['Bahir Dar', 'Gondar', 'Dessie', 'Lalibela'] },
    { name: 'Tigray', cities: ['Mekelle', 'Adigrat', 'Axum'] },
    { name: 'Sidama', cities: ['Hawassa', 'Yirgalem'] },
    { name: 'Dire Dawa', cities: ['Dire Dawa City'] },
  ],
  eg: [
    { name: 'Cairo', cities: ['Cairo Downtown', 'Heliopolis', 'Nasr City', 'Maadi', 'Zamalek', '6th October', 'Shubra'] },
    { name: 'Alexandria', cities: ['Alexandria Downtown', 'Borg El Arab', 'Montaza', 'Miami'] },
    { name: 'Giza', cities: ['Giza City', 'Haram', 'Dokki', 'Mohandeseen'] },
    { name: 'Luxor', cities: ['Luxor City', 'Karnak'] },
    { name: 'Aswan', cities: ['Aswan City', 'Edfu'] },
    { name: 'Port Said', cities: ['Port Said City'] },
    { name: 'Suez', cities: ['Suez City', 'Ain Sokhna'] },
  ],
  us: [
    { name: 'California', cities: ['Los Angeles', 'San Francisco', 'San Diego', 'Sacramento', 'San Jose', 'Oakland'] },
    { name: 'New York', cities: ['New York City', 'Buffalo', 'Rochester', 'Albany', 'Syracuse'] },
    { name: 'Texas', cities: ['Houston', 'Dallas', 'Austin', 'San Antonio', 'Fort Worth'] },
    { name: 'Florida', cities: ['Miami', 'Orlando', 'Tampa', 'Jacksonville', 'Fort Lauderdale'] },
    { name: 'Illinois', cities: ['Chicago', 'Aurora', 'Naperville', 'Springfield'] },
    { name: 'Washington', cities: ['Seattle', 'Spokane', 'Tacoma', 'Bellevue'] },
    { name: 'Massachusetts', cities: ['Boston', 'Cambridge', 'Worcester', 'Springfield'] },
    { name: 'Georgia', cities: ['Atlanta', 'Savannah', 'Augusta', 'Columbus'] },
    { name: 'Colorado', cities: ['Denver', 'Colorado Springs', 'Boulder', 'Fort Collins'] },
    { name: 'Arizona', cities: ['Phoenix', 'Tucson', 'Mesa', 'Scottsdale'] },
  ],
  gb: [
    { name: 'England', cities: ['London', 'Manchester', 'Birmingham', 'Liverpool', 'Leeds', 'Bristol', 'Newcastle', 'Sheffield', 'Nottingham', 'Southampton'] },
    { name: 'Scotland', cities: ['Edinburgh', 'Glasgow', 'Aberdeen', 'Dundee', 'Inverness'] },
    { name: 'Wales', cities: ['Cardiff', 'Swansea', 'Newport', 'Wrexham'] },
    { name: 'Northern Ireland', cities: ['Belfast', 'Derry', 'Lisburn', 'Newry'] },
  ],
  de: [
    { name: 'Bayern', cities: ['Munich', 'Nuremberg', 'Augsburg', 'Regensburg', 'Würzburg'] },
    { name: 'Nordrhein-Westfalen', cities: ['Cologne', 'Düsseldorf', 'Dortmund', 'Essen', 'Bonn', 'Wuppertal'] },
    { name: 'Berlin', cities: ['Berlin Mitte', 'Charlottenburg', 'Friedrichshain', 'Neukölln', 'Pankow'] },
    { name: 'Hamburg', cities: ['Hamburg Mitte', 'Altona', 'Eimsbüttel', 'Harburg'] },
    { name: 'Hessen', cities: ['Frankfurt', 'Wiesbaden', 'Kassel', 'Darmstadt'] },
    { name: 'Baden-Württemberg', cities: ['Stuttgart', 'Karlsruhe', 'Freiburg', 'Heidelberg', 'Mannheim'] },
    { name: 'Sachsen', cities: ['Leipzig', 'Dresden', 'Chemnitz'] },
    { name: 'Niedersachsen', cities: ['Hanover', 'Braunschweig', 'Osnabrück', 'Göttingen'] },
  ],
  fr: [
    { name: 'Île-de-France', cities: ['Paris', 'Boulogne-Billancourt', 'Saint-Denis', 'Montreuil', 'Versailles'] },
    { name: 'Auvergne-Rhône-Alpes', cities: ['Lyon', 'Grenoble', 'Clermont-Ferrand', 'Saint-Étienne'] },
    { name: 'Provence-Alpes-Côte d\'Azur', cities: ['Marseille', 'Nice', 'Toulon', 'Aix-en-Provence', 'Avignon'] },
    { name: 'Occitanie', cities: ['Toulouse', 'Montpellier', 'Nîmes', 'Perpignan'] },
    { name: 'Nouvelle-Aquitaine', cities: ['Bordeaux', 'Limoges', 'Poitiers', 'Pau'] },
    { name: 'Hauts-de-France', cities: ['Lille', 'Amiens', 'Calais', 'Dunkirk'] },
    { name: 'Grand Est', cities: ['Strasbourg', 'Reims', 'Metz', 'Nancy'] },
  ],
  in: [
    { name: 'Maharashtra', cities: ['Mumbai', 'Pune', 'Nagpur', 'Thane', 'Nashik', 'Aurangabad'] },
    { name: 'Delhi', cities: ['New Delhi', 'Dwarka', 'Rohini', 'Saket', 'Karol Bagh'] },
    { name: 'Karnataka', cities: ['Bangalore', 'Mysore', 'Hubli', 'Mangalore', 'Belgaum'] },
    { name: 'Tamil Nadu', cities: ['Chennai', 'Coimbatore', 'Madurai', 'Tiruchirappalli', 'Salem'] },
    { name: 'Uttar Pradesh', cities: ['Lucknow', 'Kanpur', 'Agra', 'Varanasi', 'Noida', 'Ghaziabad'] },
    { name: 'West Bengal', cities: ['Kolkata', 'Howrah', 'Durgapur', 'Siliguri', 'Asansol'] },
    { name: 'Telangana', cities: ['Hyderabad', 'Warangal', 'Karimnagar'] },
    { name: 'Gujarat', cities: ['Ahmedabad', 'Surat', 'Vadodara', 'Rajkot', 'Bhavnagar'] },
    { name: 'Rajasthan', cities: ['Jaipur', 'Udaipur', 'Jodhpur', 'Kota', 'Bikaner'] },
    { name: 'Kerala', cities: ['Kochi', 'Thiruvananthapuram', 'Kozhikode', 'Thrissur'] },
  ],
  ae: [
    { name: 'Dubai', cities: ['Dubai Marina', 'Downtown Dubai', 'Jumeirah', 'Deira', 'Business Bay', 'Mirdif', 'Al Barsha'] },
    { name: 'Abu Dhabi', cities: ['Abu Dhabi City', 'Al Ain', 'Al Reef', 'Yas Island', 'Saadiyat Island'] },
    { name: 'Sharjah', cities: ['Sharjah City', 'Al Majaz', 'Al Nahda', 'Muwaileh'] },
    { name: 'Ajman', cities: ['Ajman City', 'Al Jurf'] },
    { name: 'Ras Al Khaimah', cities: ['RAK City', 'Al Marjan Island'] },
    { name: 'Fujairah', cities: ['Fujairah City', 'Dibba Al Fujairah'] },
  ],
  br: [
    { name: 'São Paulo', cities: ['São Paulo City', 'Campinas', 'Santos', 'São Bernardo', 'Guarulhos'] },
    { name: 'Rio de Janeiro', cities: ['Rio de Janeiro City', 'Niterói', 'Duque de Caxias', 'Nova Iguaçu'] },
    { name: 'Minas Gerais', cities: ['Belo Horizonte', 'Uberlândia', 'Contagem', 'Juiz de Fora'] },
    { name: 'Bahia', cities: ['Salvador', 'Feira de Santana', 'Vitória da Conquista'] },
    { name: 'Distrito Federal', cities: ['Brasília', 'Taguatinga', 'Ceilândia', 'Planaltina'] },
    { name: 'Paraná', cities: ['Curitiba', 'Londrina', 'Maringá', 'Ponta Grossa'] },
    { name: 'Rio Grande do Sul', cities: ['Porto Alegre', 'Caxias do Sul', 'Pelotas', 'Santa Maria'] },
    { name: 'Pernambuco', cities: ['Recife', 'Olinda', 'Jaboatão', 'Caruaru'] },
  ],
  cn: [
    { name: 'Beijing', cities: ['Beijing City', 'Haidian', 'Chaoyang', 'Dongcheng', 'Fengtai'] },
    { name: 'Shanghai', cities: ['Shanghai City', 'Pudong', 'Puxi', 'Huangpu', 'Jing\'an'] },
    { name: 'Guangdong', cities: ['Guangzhou', 'Shenzhen', 'Dongguan', 'Foshan', 'Zhuhai'] },
    { name: 'Zhejiang', cities: ['Hangzhou', 'Ningbo', 'Wenzhou', 'Shaoxing', 'Jiaxing'] },
    { name: 'Jiangsu', cities: ['Nanjing', 'Suzhou', 'Wuxi', 'Changzhou', 'Nantong'] },
    { name: 'Sichuan', cities: ['Chengdu', 'Mianyang', 'Deyang', 'Yibin'] },
    { name: 'Hubei', cities: ['Wuhan', 'Xiangyang', 'Yichang', 'Jingzhou'] },
    { name: 'Fujian', cities: ['Fuzhou', 'Xiamen', 'Quanzhou', 'Zhangzhou'] },
  ],
  jp: [
    { name: 'Tokyo', cities: ['Shinjuku', 'Shibuya', 'Minato', 'Chiyoda', 'Taito', 'Edogawa', 'Setagaya'] },
    { name: 'Osaka', cities: ['Osaka City', 'Sakai', 'Higashiosaka', 'Toyonaka'] },
    { name: 'Kanagawa', cities: ['Yokohama', 'Kawasaki', 'Sagamihara', 'Fujisawa'] },
    { name: 'Aichi', cities: ['Nagoya', 'Toyota', 'Okazaki', 'Ichinomiya'] },
    { name: 'Fukuoka', cities: ['Fukuoka City', 'Kitakyushu', 'Kurume'] },
    { name: 'Hokkaido', cities: ['Sapporo', 'Hakodate', 'Asahikawa', 'Otaru'] },
    { name: 'Kyoto', cities: ['Kyoto City', 'Uji', 'Kizugawa'] },
    { name: 'Chiba', cities: ['Chiba City', 'Funabashi', 'Matsudo', 'Ichikawa'] },
  ],
  au: [
    { name: 'New South Wales', cities: ['Sydney', 'Newcastle', 'Wollongong', 'Central Coast', 'Albury'] },
    { name: 'Victoria', cities: ['Melbourne', 'Geelong', 'Ballarat', 'Bendigo', 'Shepparton'] },
    { name: 'Queensland', cities: ['Brisbane', 'Gold Coast', 'Sunshine Coast', 'Townsville', 'Cairns'] },
    { name: 'Western Australia', cities: ['Perth', 'Fremantle', 'Bunbury', 'Geraldton', 'Albany'] },
    { name: 'South Australia', cities: ['Adelaide', 'Mount Gambier', 'Whyalla', 'Port Augusta'] },
    { name: 'ACT', cities: ['Canberra', 'Belconnen', 'Tuggeranong'] },
    { name: 'Tasmania', cities: ['Hobart', 'Launceston', 'Devonport'] },
    { name: 'Northern Territory', cities: ['Darwin', 'Alice Springs', 'Palmerston'] },
  ],
  ca: [
    { name: 'Ontario', cities: ['Toronto', 'Ottawa', 'Mississauga', 'Hamilton', 'London', 'Kitchener', 'Windsor'] },
    { name: 'British Columbia', cities: ['Vancouver', 'Victoria', 'Surrey', 'Burnaby', 'Richmond', 'Kelowna'] },
    { name: 'Quebec', cities: ['Montreal', 'Quebec City', 'Laval', 'Gatineau', 'Longueuil'] },
    { name: 'Alberta', cities: ['Calgary', 'Edmonton', 'Red Deer', 'Lethbridge', 'Fort McMurray'] },
    { name: 'Manitoba', cities: ['Winnipeg', 'Brandon', 'Steinbach'] },
    { name: 'Saskatchewan', cities: ['Saskatoon', 'Regina', 'Prince Albert', 'Moose Jaw'] },
    { name: 'Nova Scotia', cities: ['Halifax', 'Dartmouth', 'Sydney'] },
    { name: 'New Brunswick', cities: ['Moncton', 'Saint John', 'Fredericton'] },
  ],
};

export function getCountryStates(code: string): StateEntry[] {
  return countryStates[code.toLowerCase()] || [];
}
